# Generated by Django 4.2.3 on 2023-08-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
