# Generated by Django 4.2.3 on 2023-08-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mailingmessage', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время старта'),
        ),
    ]
