# Generated by Django 4.2.3 on 2023-08-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0003_mailinglog_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('set_status', 'Статус рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
