# Generated by Django 4.2.3 on 2023-08-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0004_alter_mailingsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mailing.buyer', verbose_name='Сообщение'),
        ),
    ]
