# Generated by Django 4.2.3 on 2023-08-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='time',
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время старта'),
        ),
    ]
