# Generated by Django 4.2.3 on 2023-08-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active', 'Активность')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
