# Generated by Django 4.2.3 on 2023-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='признак публикации'),
        ),
    ]
